
const roleRowNames = [
    'add_reactions',
    'administrator',
    'attach_files',
    'ban_members',
    'change_nickname',
    'connect',
    'create_expressions',
    'create_instant_invite',
    'create_private_threads',
    'create_public_threads',
    'deafen_members',
    'embed_links',
    'kick_members',
    'manage_channels',
    'manage_emojis_and_stickers',
    'manage_events',
    'manage_expressions',
    'manage_guild',
    'manage_messages',
    'manage_nicknames',
    'manage_permissions',
    'manage_threads',
    'manage_webhooks',
    'mention_everyone',
    'moderate_members',
    'move_members',
    'mute_members',
    'priority_speaker',
    'read_message_history',
    'read_messages',
    'request_to_speak',
    'send_messages',
    'send_messages_in_threads',
    'send_tts_messages',
    'send_voice_messages',
    'speak',
    'stream',
    'use_application_commands',
    'use_embedded_activities',
    'use_external_emojis',
    'use_external_sounds',
    'use_external_stickers',
    'use_soundboard',
    'use_voice_activation',
    'value',
    'view_audit_log',
    'view_guild_insights'
]

// If we add settings other than permissions, we may need to use toggleButton,
// e.g.,
// const roleRowTypes = ['slider', 'slider', 'toggleButton', 'toggleButton'];
const roleRowTypes = [
    'slider',
    'aslider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider',
    'slider'
];

const channelRowNames = [
  'age_restriction',
  'view_channel'
]; 

const channelRowTypes = [
  'toggleButton',
  'toggleButton'
];

