export const textDisplayedText = {
    'add_reactions': "User can add reactions to messages.",
    'attach_files': "User can send files in their messages.",
    'create_instant_invite': "User can create instant invites.",
    'create_private_threads': "User can create private threads.",
    'create_public_threads': "User can create public threads.",
    'embed_links': "User’s messages will automatically be embedded by Discord.",
    'manage_channels': "User can edit, delete, or create channels in the server.",
    'manage_messages': "User can delete or pin messages in a text channel.",
    'manage_permissions': "User can create or edit roles less than their role’s position.",
    'manage_threads': "User can manage threads.",
    'manage_webhooks': "User can create, edit, or delete webhooks.",
    'mention_everyone': "User’s @everyone or @here will mention everyone in the text channel.",
    'read_message_history': "User can read a text channel’s previous messages.",
    'send_messages': "User can send messages from all or specific text channels.",
    'send_messages_in_threads': "User can send messages in threads.",
    'send_tts_messages': "User can send TTS messages from all or specific text channels.",
    'send_voice_messages': "User can send voice messages.",
    'use_application_commands': "User can use slash commands.",
    'use_embedded_activities': "User can launch an embedded application in a Voice channel.",
    'use_external_emojis': "User can use emojis from other servers.",
    'use_external_stickers': "User can use stickers from other servers.",
    'view_channel': "User can read messages from all or specific text channels."
}

export const voiceDisplayedText = {
    'add_reactions': "User can add reactions to messages.",
    'attach_files': "User can send files in their messages.",
    'create_events': 'User can create events.',
    'connect': "User can connect to a voice channel.",
    'create_instant_invite': "User can create instant invites.",
    'deafen_members': "User can deafen other users.",
    'embed_links': "User’s messages will automatically be embedded by Discord.",
    'manage_channels': "User can edit, delete, or create channels in the server.",
    'manage_events': "User can manage server events.",
    'manage_messages': "User can delete or pin messages in a text channel.",
    'manage_permissions': "User can create or edit roles less than their role’s position.",
    'mention_everyone': "User’s @everyone or @here will mention everyone in the text channel.",
    'move_members': "User can move users between other voice.",
    'mute_members': "User can mute other users.",
    'priority_speaker': "User’s @everyone or @here will mention everyone in the text channel.",
    'read_message_history': "User can read a text channel’s previous messages.",
    'send_messages': "User can send messages from all or specific text channels.",
    'send_tts_messages': "User can send TTS messages from all or specific text channels.",
    'send_voice_messages': "User can send voice messages.",
    'speak': "User can speak in a voice channel.",
    'stream': "User can stream in a voice channel.",
    'use_application_commands': "User can use slash commands.",
    'use_embedded_activities': "User can launch an embedded application in a Voice channel.",
    'use_external_emojis': "User can use emojis from other servers.",
    'use_external_sounds': "User can use sounds from other servers.",
    'use_external_stickers': "User can use stickers from other servers.",
    'use_soundboard': "User can use the soundboard.",
    'use_voice_activation': "User can use voice activation in voice channels.",
    'view_channel': "User can read messages from all or specific text channels.",
}

export const categoryDisplayedText = {
    'add_reactions': "User can add reactions to messages.",
    'attach_files': "User can send files in their messages.",
    'connect': "User can connect to a voice channel.",
    'create_instant_invite': "User can create instant invites.",
    'create_private_threads': "User can create private threads.",
    'create_public_threads': "User can create public threads.",
    'deafen_members': "User can deafen other users.",
    'embed_links': "User’s messages will automatically be embedded by Discord.",
    'manage_channels': "User can edit, delete, or create channels in the server.",
    'manage_events': "User can manage server events.",
    'manage_messages': "User can delete or pin messages in a text channel.",
    'manage_permissions': "User can create or edit roles less than their role’s position.",
    'manage_threads': "User can manage threads.",
    'manage_webhooks': "User can create, edit, or delete webhooks.",
    'mention_everyone': "User’s @everyone or @here will mention everyone in the text channel.",
    'move_members': "User can move users between other voice.",
    'mute_members': "User can mute other users.",
    'priority_speaker': "User’s @everyone or @here will mention everyone in the text channel.",
    'read_message_history': "User can read a text channel’s previous messages.",
    'request_to_speak': "User can request to speak in a stage channel.",
    'send_messages': "User can send messages from all or specific text channels.",
    'send_messages_in_threads': "User can send messages in threads.",
    'send_tts_messages': "User can send TTS messages from all or specific text channels.",
    'send_voice_messages': "User can send voice messages.",
    'speak': "User can speak in a voice channel.",
    'stream': "User can stream in a voice channel.",
    'use_application_commands': "User can use slash commands.",
    'use_embedded_activities': "User can launch an embedded application in a Voice channel.",
    'use_external_emojis': "User can use emojis from other servers.",
    'use_external_sounds': "User can use sounds from other servers.",
    'use_external_stickers': "User can use stickers from other guilds.",
    'use_soundboard': "User can use the soundboard.",
    'use_voice_activation': "User can use voice activation in voice channels.",
    'view_channel': "User can read messages from all or specific text channels."
}

export const roleDisplayedText = {
    'add_reactions': "User can add reactions to messages.",
    'administrator': "User is an administrator. This overrides all other permissions,.",
    'attach_files': "User can send files in their messages.",
    'ban_members': "User can ban users from the server.",
    'change_nickname': "User can change their nickname in the server.",
    'connect': "User can connect to a voice channel.",
    'create_expressions': "User can create emojis, stickers, and soundboard sounds.",
    'create_instant_invite': "User can create instant invites.",
    'create_private_threads': "User can create private threads.",
    'create_public_threads': "User can create public threads.",
    'deafen_members': "User can deafen other users.",
    'embed_links': "User’s messages will automatically be embedded by Discord.",
    'external_emojis': "User can use emojis from other servers.",
    'external_stickers': "User can use stickers from other servers.",
    'kick_members': "User can kick users from the server.",
    'manage_channels': "User can edit, delete, or create channels in the server.",
    'manage_events': "User can manage server events.",
    'manage_expressions': "User can edit or delete emojis, stickers, and soundboard sounds.",
    'manage_guild': "User can edit server properties.",
    'manage_messages': "User can delete or pin messages in a text channel.",
    'manage_nicknames': "User can change other user’s nickname in the server.",
    'manage_roles': "User can create or edit roles less than their role’s position.",
    'manage_threads': "User can manage threads.",
    'manage_webhooks': "User can create, edit, or delete webhooks.",
    'mention_everyone': "User’s @everyone or @here will mention everyone in the text channel.",
    'moderate_members': "User can time out other members.",
    'move_members': "User can move users between other voice.",
    'mute_members': "User can mute other users.",
    'priority_speaker': "User’s @everyone or @here will mention everyone in the text channel.",
    'read_message_history': "User can read a text channel’s previous messages.",
    'read_messages': "User can read messages from all or specific text channels.",
    'request_to_speak': "User can request to speak in a stage channel.",
    'send_messages': "User can send messages from all or specific text channels.",
    'send_messages_in_threads': "User can send messages in threads.",
    'send_tts_messages': "User can send TTS messages from all or specific text channels.",
    'send_voice_messages': "User can send voice messages.",
    'speak': "User can speak in a voice channel.",
    'stream': "User can stream in a voice channel.",
    'use_application_commands': "User can use slash commands.",
    'use_embedded_activities': "User can launch an embedded application in a Voice channel.",
    'use_external_emojis': "User can use emojis from other servers.",
    'use_external_sounds': "User can use sounds from other servers.",
    'use_soundboard': "User can use the soundboard.",
    'use_voice_activation': "User can use voice activation in voice channels.",
    'view_audit_log': "user can view the server’s audit log.",
    'view_guild_insights': "User can view the server’s insights."
}